### ISSUE TITLE
Test 11/05/2015

### ISSUE THREAD

**Issue by birdyhuang** [ipop-project/controllers#45]
1. The xxx/framework/CFx.py file has an indent problem in line 284
2. The instruction is a little bit confusing since the _ipop-tincan-x86_64_ file is not in the controllers directory. Where to run the command is important as it needs to locate the module. For example, following the instruction, I will end up in the directory of _controllers/controller_. But the Controller.py module cannot be found with command `controller.Controller` when I'm in _controllers/controller_. 
3. Why do we need to output the stdout on the screen? 
4. Should we mention that the _username_ in the xxx_config.json file is _username@host_ rather than simply _username_?
5. When we run the tincan, shouldn't we keep it in the background with `&` rather than `"`?

**Comment by ssabogal** [comment]
1. I believe Ken has fixed this issue.
2. I think you're right here; you must be in ```controllers/``` to issue that command.
3. This is a mistake (at least for the default usage).
4. Not necessarily; this flag can sometimes be either one of _username_ or _username@hostname_. The ```xmpp_host``` flag has some significance to this.
5. This is a mistake.

Fixes:
```sudo ./ipop-tincan-x86_64"``` should probably be: ```sudo ./ipop-tincan &> tin.log &``` since:
* this process should be in the background
* its output should be redirected to some log file
* only 64-bit will be supported for Linux distros and (I think) only 32-bit will be supported for Windows allows for the simplified naming of IPOP-Tincan.

The README should be reworded that the controller is executed from ```<path to controllers>/controllers/``` (something like this).

**Comment by saumitraaditya** [comment]
All points addressed.
